apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-core.fullname" . }}
  labels:
    {{- include "event-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.httpPort }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "event-core.selectorLabels" . | nindent 4 }}
